name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Initialize Go module
        run: |
          go mod init steamgrid
          go mod tidy
          mkdir out
      
      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o steamgrid.exe
          GOOS=windows GOARCH=arm64 go build -o steamgrid-arm64.exe

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o steamgrid
          GOOS=linux GOARCH=arm64 go build -o steamgrid-arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: windows-amd64
            path: steamgrid.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-arm64
          path: steamgrid-arm64.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64
          path: steamgrid

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: steamgrid-arm64