name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Initialize Go module
        run: |
          go mod init steamgrid
          go mod tidy
      
      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o steamgrid.exe ./cmd/steamgrid
          GOOS=windows GOARCH=arm64 go build -o steamgrid-arm64.exe ./cmd/steamgrid

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o steamgrid ./cmd/steamgrid
          GOOS=linux GOARCH=arm64 go build -o steamgrid-arm64 ./cmd/steamgrid